(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const state = { cues: [], source: false, name: "captions" };
  const input = $("fileInput"); const drop = $("dropZone"); const status = $("fileStatus"); const work = $("work");
  function ms(value) { const parts = value.trim().replace(",", ".").split(":").map(Number); if (parts.length === 3) return (parts[0] * 3600 + parts[1] * 60 + parts[2]) * 1000; if (parts.length === 2) return (parts[0] * 60 + parts[1]) * 1000; return NaN; }
  function parseSrt(text) { return text.replace(/\r/g, "").trim().split(/\n{2,}/).map((block) => { const lines = block.split("\n"); const index = lines.findIndex((line) => line.includes("-->")); if (index < 0) return null; const [start, end] = lines[index].split("-->").map(ms); return { start, end, text: lines.slice(index + 1).join("\n") }; }).filter(Boolean); }
  function parseVtt(text) { return parseSrt(text.replace(/^WEBVTT[^\n]*\n+/i, "")); }
  function parseSbv(text) { return text.replace(/\r/g, "").trim().split(/\n{2,}/).map((block) => { const lines = block.split("\n"); const times = lines[0].split(","); if (times.length !== 2) return null; return { start: ms(times[0]), end: ms(times[1]), text: lines.slice(1).join("\n") }; }).filter(Boolean); }
  function parseAss(text) { const cues = []; for (const line of text.split(/\r?\n/)) { if (!/^Dialogue:/i.test(line)) continue; const fields = line.replace(/^Dialogue:\s*/i, "").split(","); if (fields.length < 10) continue; cues.push({ start: ms(fields[1]), end: ms(fields[2]), text: fields.slice(9).join(",").replace(/\\N/g, "\n").replace(/\{[^}]*\}/g, "") }); } return cues; }
  function parseText(text, name = "captions.srt") { const ext = (name.split(".").pop() || "").toLowerCase(); return ext === "vtt" ? parseVtt(text) : ext === "sbv" ? parseSbv(text) : ext === "ass" ? parseAss(text) : parseSrt(text); }
  function pad(value, length = 2) { return String(value).padStart(length, "0"); }
  function time(value, format) { const milliseconds = Math.max(0, Math.round(value)); const hours = Math.floor(milliseconds / 3600000); const minutes = Math.floor(milliseconds % 3600000 / 60000); const seconds = Math.floor(milliseconds % 60000 / 1000); const remainder = milliseconds % 1000; if (format === "ass") return `${hours}:${pad(minutes)}:${pad(seconds)}.${pad(Math.floor(remainder / 10))}`; if (format === "sbv") return `${hours}:${pad(minutes)}:${pad(seconds)}.${pad(remainder, 3)}`; return `${pad(hours)}:${pad(minutes)}:${pad(seconds)}${format === "srt" ? "," : "."}${pad(remainder, 3)}`; }
  function shifted(cues = state.cues, offset = Number($("offset")?.value) || 0) { const amount = Math.max(-86400000, Math.min(86400000, offset)); return cues.map((cue) => ({ ...cue, start: Math.max(0, cue.start + amount), end: Math.max(0, cue.end + amount) })); }
  function output(format, cues = state.cues, offset = Number($("offset")?.value) || 0) { const converted = shifted(cues, offset); if (format === "srt") return converted.map((cue, index) => `${index + 1}\r\n${time(cue.start, "srt")} --> ${time(cue.end, "srt")}\r\n${cue.text}\r\n`).join("\r\n"); if (format === "vtt") return "WEBVTT\r\n\r\n" + converted.map((cue) => `${time(cue.start, "vtt")} --> ${time(cue.end, "vtt")}\r\n${cue.text}\r\n`).join("\r\n"); if (format === "sbv") return converted.map((cue) => `${time(cue.start, "sbv")},${time(cue.end, "sbv")}\r\n${cue.text}\r\n`).join("\r\n"); return `[Script Info]\r\nScriptType: v4.00+\r\n\r\n[V4+ Styles]\r\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\r\nStyle: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H64000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,24,1\r\n\r\n[Events]\r\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n` + converted.map((cue) => `Dialogue: 0,${time(cue.start, "ass")},${time(cue.end, "ass")},Default,,0,0,0,,${cue.text.replace(/\n/g, "\\N")}`).join("\r\n"); }
  function render() { const rows = $("rows"); rows.replaceChildren(...state.cues.slice(0, 200).map((cue, index) => { const row = document.createElement("tr"); [index + 1, time(cue.start, "vtt"), time(cue.end, "vtt"), cue.text].forEach((value) => { const cell = document.createElement("td"); cell.textContent = value; row.append(cell); }); return row; })); const invalid = state.cues.filter((cue) => !Number.isFinite(cue.start) || !Number.isFinite(cue.end) || cue.end < cue.start).length; $("validation").textContent = `${state.cues.length} captions found${invalid ? ` · ${invalid} timing problems detected` : ""}.`; work.classList.remove("hidden"); window.dispatchEvent(new CustomEvent("captionshift:data-loaded")); }
  function load(file, sample = false) { if (!sample && !SuiteGate.mayOpenRealDocument()) { SuiteGate.showUpgrade(); return; } if (!file || file.size > 5 * 1024 * 1024) { SuiteGate.message("Choose a subtitle file smaller than 5 MB."); return; } const reader = new FileReader(); reader.onload = () => { try { state.cues = parseText(String(reader.result), file.name); if (!state.cues.length) throw Error("No valid caption cues were found."); state.source = sample; state.name = file.name.replace(/\.[^.]+$/, ""); const extension = (file.name.split(".").pop() || "").toLowerCase(); $("format").value = extension === "vtt" ? "srt" : extension === "srt" ? "vtt" : "srt"; status.textContent = `${file.name} · ${state.cues.length} captions`; render(); SuiteGate.update(sample); } catch (error) { SuiteGate.message(error.message); } }; reader.readAsText(file); }
  input.addEventListener("change", (event) => load(event.target.files[0])); drop.addEventListener("dragover", (event) => event.preventDefault()); drop.addEventListener("drop", (event) => { event.preventDefault(); load(event.dataTransfer.files[0]); });
  $("sampleBtn").addEventListener("click", () => load(new File(["1\n00:00:01,000 --> 00:00:04,000\nWelcome to CaptionShift.\n\n2\n00:00:05,000 --> 00:00:08,500\nYour subtitle file stays in this browser."], "sample.srt", { type: "text/plain" }), true));
  $("clearBtn").addEventListener("click", () => { state.cues = []; input.value = ""; status.textContent = "No file selected"; work.classList.add("hidden"); SuiteGate.setActive(false); });
  $("download").addEventListener("click", () => { const format = $("format").value; const anchor = document.createElement("a"); anchor.href = URL.createObjectURL(new Blob([output(format)], { type: "text/plain" })); anchor.download = `${state.name}.${format}`; anchor.click(); setTimeout(() => URL.revokeObjectURL(anchor.href), 1000); if (!state.source) SuiteGate.markUsed(); });
  window.CaptionShiftCore = { state, parseText, render, output, shifted, time };
  window.dispatchEvent(new Event("captionshift:ready"));
})();
