(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const state = { contacts: [], source: false, name: "contacts", inputType: "vcf", headers: [] };
  const input = $("fileInput"), drop = $("dropZone"), status = $("fileStatus"), work = $("work");
  function parseLine(line) { const values = []; let value = "", quoted = false; for (let index = 0; index < line.length; index += 1) { const char = line[index]; if (char === '"') { if (quoted && line[index + 1] === '"') { value += '"'; index += 1; } else quoted = !quoted; } else if (char === "," && !quoted) { values.push(value.trim()); value = ""; } else value += char; } values.push(value.trim()); return values; }
  function parseCsv(text) { const lines = text.replace(/^\uFEFF/, "").split(/\r?\n/).filter(Boolean), headers = parseLine(lines.shift()).map((value) => value.toLowerCase()); state.headers = headers; return lines.map((line) => { const values = parseLine(line), get = (...names) => { for (const name of names) { const index = headers.indexOf(name); if (index >= 0) return values[index] || ""; } return ""; }; return { name: get("name", "full name", "fullname"), first: get("first name", "firstname", "first"), last: get("last name", "lastname", "last"), email: get("email", "email address"), phone: get("phone", "phone number", "mobile"), org: get("organization", "company", "org"), address: get("address", "street") }; }); }
  function unfold(text) { return text.replace(/\r?\n[ \t]/g, ""); }
  function parseVcf(text) { return unfold(text).split(/BEGIN:VCARD/i).slice(1).map((block) => { const value = (key) => { const match = block.match(new RegExp(`(?:^|\\n)${key}(?:;[^:]*)?:([^\\r\\n]*)`, "i")); return match ? match[1].replace(/\\n/g, " ").replace(/\\,/g, ",").trim() : ""; }; const names = value("N").split(";"); return { name: value("FN") || [names[1], names[0]].filter(Boolean).join(" "), first: names[1] || "", last: names[0] || "", email: value("EMAIL"), phone: value("TEL"), org: value("ORG"), address: value("ADR").split(";").filter(Boolean).join(", ") }; }); }
  function escapeVcf(value) { return String(value || "").replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/,/g, "\\,").replace(/;/g, "\\;"); }
  function csvValue(value) { const text = String(value || ""); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
  function toVcf(contacts = state.contacts) { return contacts.map((contact) => `BEGIN:VCARD\r\nVERSION:3.0\r\nN:${escapeVcf(contact.last)};${escapeVcf(contact.first)};;;\r\nFN:${escapeVcf(contact.name || [contact.first, contact.last].filter(Boolean).join(" "))}\r\n${contact.org ? `ORG:${escapeVcf(contact.org)}\r\n` : ""}${contact.email ? `EMAIL:${escapeVcf(contact.email)}\r\n` : ""}${contact.phone ? `TEL:${escapeVcf(contact.phone)}\r\n` : ""}${contact.address ? `ADR:;;${escapeVcf(contact.address)};;;;\r\n` : ""}END:VCARD\r\n`).join(""); }
  function toCsv(contacts = state.contacts, mapping = {}) { const fields = [["name", "Name"], ["first", "First Name"], ["last", "Last Name"], ["email", "Email"], ["phone", "Phone"], ["org", "Organization"], ["address", "Address"]].map(([field, label]) => [field, mapping[field] || label]); return [fields.map(([, label]) => csvValue(label)).join(","), ...contacts.map((contact) => fields.map(([field]) => csvValue(contact[field])).join(","))].join("\r\n"); }
  function render() { const body = $("rows"); body.replaceChildren(...state.contacts.slice(0, 200).map((contact) => { const row = document.createElement("tr"); [contact.name, contact.email, contact.phone, contact.org].forEach((value) => { const cell = document.createElement("td"); cell.textContent = value || "—"; row.append(cell); }); return row; })); $("validation").textContent = `${state.contacts.length.toLocaleString()} contact${state.contacts.length === 1 ? "" : "s"} ready for conversion.`; work.classList.remove("hidden"); window.dispatchEvent(new CustomEvent("contactcraft:data-loaded")); }
  function load(file, sample = false) { if (!sample && !window.SuiteGate.mayOpenRealDocument()) { window.SuiteGate.showUpgrade(); return; } if (!file || file.size > 10 * 1024 * 1024) { window.SuiteGate.message("Choose a VCF or CSV file smaller than 10 MB."); return; } const reader = new FileReader(); reader.onload = () => { try { const text = String(reader.result), isVcf = /\.vcf$|\.vcard$/i.test(file.name) || /BEGIN:VCARD/i.test(text); state.contacts = isVcf ? parseVcf(text) : parseCsv(text); if (!state.contacts.length) throw Error("No contacts were found."); Object.assign(state, { source: sample, name: file.name.replace(/\.[^.]+$/, ""), inputType: isVcf ? "vcf" : "csv" }); $("format").value = isVcf ? "csv" : "vcf"; status.textContent = `${file.name} · ${state.contacts.length} contacts`; render(); window.SuiteGate.update(sample); } catch (error) { window.SuiteGate.message(error.message); } }; reader.readAsText(file); }
  async function download(format = $("format").value, contacts = state.contacts, mapping = {}) { if (!state.source && window.SuiteGate.used()) { window.SuiteGate.showUpgrade(); return; } const content = format === "csv" ? toCsv(contacts, mapping) : toVcf(contacts); const blob = new Blob([content], { type: format === "csv" ? "text/csv" : "text/vcard" }), anchor = document.createElement("a"); anchor.href = URL.createObjectURL(blob); anchor.download = `${state.name}.${format}`; anchor.click(); setTimeout(() => URL.revokeObjectURL(anchor.href), 1000); if (!state.source) window.SuiteGate.markUsed(); }
  input.addEventListener("change", (event) => load(event.target.files[0])); drop.addEventListener("dragover", (event) => event.preventDefault()); drop.addEventListener("drop", (event) => { event.preventDefault(); load(event.dataTransfer.files[0]); });
  $("sampleBtn").addEventListener("click", () => load(new File([`BEGIN:VCARD\nVERSION:3.0\nFN:Avery Stone\nN:Stone;Avery;;;\nEMAIL:avery@example.com\nTEL:+1 208 555 0142\nORG:Northwind Studio\nEND:VCARD\nBEGIN:VCARD\nVERSION:3.0\nFN:Jordan Lee\nN:Lee;Jordan;;;\nEMAIL:jordan@example.com\nTEL:+1 509 555 0188\nEND:VCARD`], "sample.vcf", { type: "text/vcard" }), true));
  $("clearBtn").addEventListener("click", () => { state.contacts = []; input.value = ""; status.textContent = "No file selected"; work.classList.add("hidden"); window.SuiteGate.setActive(false); }); $("download").addEventListener("click", () => download());
  window.ContactCraftCore = { state, render, download, toCsv, toVcf };
  window.dispatchEvent(new Event("contactcraft:ready"));
})();
