import test from "node:test";
import assert from "node:assert/strict";
import { createHmac, webcrypto } from "node:crypto";
import { handleRequest, summarizeEntitlements } from "../worker.js";

if (!globalThis.crypto) globalThis.crypto = webcrypto;

const secret = "paddle-test-secret";
const signingSecret = "license-test-secret";
const prices = { standard: "pri_ledger_standard", plus: "pri_ledger_plus", bundle: "pri_bundle" };
const envBase = () => ({ PADDLE_WEBHOOK_SECRET: secret, LICENSE_SIGNING_SECRET: signingSecret, PADDLE_PRICE_LEDGERLIFT_STANDARD: prices.standard, PADDLE_PRICE_LEDGERLIFT_PLUS: prices.plus, PADDLE_PRICE_SUITE_BUNDLE: prices.bundle, DEVELOPMENT: "true", ASSETS: { fetch: async (request) => new Response(`static:${new URL(request.url).pathname}`) } });

class FakeStatement {
  constructor(db, sql) { this.db = db; this.sql = sql; this.args = []; }
  bind(...args) { this.args = args; return this; }
  async first() { return this.db.first(this.sql, this.args); }
  async all() { return this.db.all(this.sql, this.args); }
  async run() { return this.db.run(this.sql, this.args); }
}

class FakeDb {
  constructor() { this.events = new Map(); this.customers = []; this.entitlements = []; this.codes = []; this.activations = []; this.guards = []; this.adjustments = []; this.restores = []; this.failNext = null; }
  prepare(sql) { return new FakeStatement(this, sql); }
  async first(sql, a) {
    if (sql.includes("SELECT status,outcome,processing_token,processing_started_at")) return this.events.get(a[0]) || null;
    if (sql.includes("SELECT id FROM customers")) return this.customers.find((row) => row.paddle_customer_id === a[0]) || null;
    if (sql.includes("SELECT id FROM entitlements WHERE transaction_id")) return this.entitlements.find((row) => row.transaction_id === a[0] && row.product_key === a[1] && row.plan_key === a[2]) || null;
    if (sql.includes("SELECT transaction_id,status FROM entitlement_purchase_guards")) return this.guards.find((row) => row.customer_id === a[0] && row.product_key === a[1] && row.plan_key === a[2] && row.status === "active") || null;
    if (sql.includes("SELECT id FROM activation_codes WHERE entitlement_id")) return this.codes.find((row) => row.entitlement_id === a[0]) || null;
    if (sql.includes("SELECT ac.id, ac.entitlement_id")) { const code = this.codes.find((row) => row.code_hash === a[0]); const ent = code && this.entitlements.find((row) => row.id === code.entitlement_id); return code && ent ? { ...code, product_key: ent.product_key, plan_key: ent.plan_key, status: ent.status } : null; }
    if (sql.includes("SELECT id,token_id FROM activations")) return this.activations.find((row) => row.entitlement_id === a[0] && row.installation_id_hash === a[1] && !row.revoked_at) || null;
    if (sql.includes("SELECT a.revoked_at")) { const activation = this.activations.find((row) => row.token_id === a[0]); const ent = activation && this.entitlements.find((row) => row.id === activation.entitlement_id); return activation && ent ? { revoked_at: activation.revoked_at, status: ent.status, product_key: ent.product_key, plan_key: ent.plan_key } : null; }
    if (sql.includes("COUNT(*)")) return { count: this.customers.filter((row) => row.normalized_email === a[0]).length };
    return null;
  }
  async all(sql, a) {
    if (sql.includes("FROM paddle_adjustments WHERE transaction_id")) return { results: this.adjustments.filter((row) => row.transaction_id === a[0]) };
    if (sql.includes("FROM entitlements WHERE transaction_id")) return { results: this.entitlements.filter((row) => row.transaction_id === a[0]) };
    return { results: [] };
  }
  async run(sql, a) {
    if (this.failNext === "event_insert" && sql.startsWith("INSERT INTO paddle_events")) { this.failNext = null; throw new Error("database unavailable"); }
    if (sql.startsWith("INSERT INTO paddle_events")) { if (this.events.has(a[0])) return { meta: { changes: 0 } }; this.events.set(a[0], { status: a[6], outcome: null, processing_token: a[7], processing_started_at: a[8] }); return { meta: { changes: 1 } }; }
    if (sql.startsWith("UPDATE paddle_events SET status = 'processing'")) { const row = this.events.get(a[2]); const canClaim = row && (row.status === "failed" || (row.status === "processing" && (!row.processing_token || !row.processing_started_at || row.processing_started_at < a[3]))); if (!canClaim) return { meta: { changes: 0 } }; row.status = "processing"; row.processing_token = a[0]; row.processing_started_at = a[1]; return { meta: { changes: 1 } }; }
    if (sql.startsWith("UPDATE paddle_events SET status = 'failed'")) { const row = this.events.get(a[2]); if (row?.processing_token === a[3]) { row.status = "failed"; row.processing_token = null; row.processing_started_at = null; } return { meta: { changes: row ? 1 : 0 } }; }
    if (sql.startsWith("UPDATE paddle_events SET status = 'fulfilled'")) { const row = this.events.get(a[2]); if (row?.processing_token === a[3]) { row.status = "fulfilled"; row.outcome = a[0]; row.processing_token = null; row.processing_started_at = null; return { meta: { changes: 1 } }; } return { meta: { changes: 0 } }; }
    if (sql.startsWith("INSERT OR IGNORE INTO entitlement_purchase_guards")) { const existing = this.guards.find((row) => (row.transaction_id === a[4] && row.product_key === a[2] && row.plan_key === a[3]) || (row.customer_id === a[1] && row.product_key === a[2] && row.plan_key === a[3] && row.status === "active")); if (!existing) this.guards.push({ id: a[0], customer_id: a[1], product_key: a[2], plan_key: a[3], transaction_id: a[4], entitlement_id: a[5], status: a[6], created_at: a[7], updated_at: a[8] }); return { meta: { changes: existing ? 0 : 1 } }; }
    if (sql.startsWith("INSERT INTO paddle_adjustments")) { const current = this.adjustments.find((row) => row.adjustment_id === a[0]); if (current) Object.assign(current, { transaction_id: a[1], customer_id: a[2], action: a[3], adjustment_type: a[4], status: a[5], effect: a[6], item_ids: a[7], updated_at: a[9] }); else this.adjustments.push({ adjustment_id: a[0], transaction_id: a[1], customer_id: a[2], action: a[3], adjustment_type: a[4], status: a[5], effect: a[6], item_ids: a[7], created_at: a[8], updated_at: a[9] }); return { meta: { changes: 1 } }; }
    if (sql.startsWith("UPDATE paddle_adjustments SET status = 'reversed'")) { let changes = 0; for (const row of this.adjustments.filter((item) => item.transaction_id === a[1] && item.action === a[2] && item.effect === "revoke" && item.adjustment_id !== a[3])) { row.status = "reversed"; row.effect = "restore"; row.updated_at = a[0]; changes += 1; } return { meta: { changes } }; }
    if (sql.startsWith("UPDATE entitlement_purchase_guards SET status = 'revoked'")) { const rows = this.guards.filter((row) => row.transaction_id === a[1] && row.product_key === a[2] && row.plan_key === a[3] && row.status === "active"); rows.forEach((row) => { row.status = "revoked"; row.updated_at = a[0]; }); return { meta: { changes: rows.length } }; }
    if (sql.startsWith("UPDATE entitlement_purchase_guards SET status = 'active'")) { const rows = this.guards.filter((row) => row.transaction_id === a[1] && row.product_key === a[2] && row.plan_key === a[3]); rows.forEach((row) => { row.status = "active"; row.updated_at = a[0]; }); return { meta: { changes: rows.length } }; }
    if (sql.startsWith("UPDATE entitlements SET status = 'revoked'")) { const row = this.entitlements.find((item) => item.id === a[3] && item.status === "active"); if (row) { row.status = "revoked"; row.revoked_at = a[0]; row.revocation_reason = a[1]; row.updated_at = a[2]; } return { meta: { changes: row ? 1 : 0 } }; }
    if (sql.startsWith("UPDATE entitlements SET status = 'active'")) { const row = this.entitlements.find((item) => item.id === a[1] && item.status === "revoked"); if (row) { row.status = "active"; row.revoked_at = null; row.revocation_reason = null; row.updated_at = a[0]; } return { meta: { changes: row ? 1 : 0 } }; }
    if (sql.startsWith("UPDATE activation_codes SET revoked_at = NULL")) { const rows = this.codes.filter((row) => row.entitlement_id === a[0]); rows.forEach((row) => { row.revoked_at = null; }); return { meta: { changes: rows.length } }; }
    if (sql.startsWith("UPDATE activation_codes SET revoked_at")) { const rows = this.codes.filter((row) => row.entitlement_id === a[1]); rows.forEach((row) => { row.revoked_at = a[0]; }); return { meta: { changes: rows.length } }; }
    if (sql.startsWith("UPDATE activations SET revoked_at = NULL")) { const rows = this.activations.filter((row) => row.entitlement_id === a[0]); rows.forEach((row) => { row.revoked_at = null; }); return { meta: { changes: rows.length } }; }
    if (sql.startsWith("UPDATE activations SET revoked_at")) { const rows = this.activations.filter((row) => row.entitlement_id === a[1] && !row.revoked_at); rows.forEach((row) => { row.revoked_at = a[0]; }); return { meta: { changes: rows.length } }; }
    if (sql.startsWith("INSERT OR IGNORE INTO customers")) { const existing = this.customers.find((row) => row.paddle_customer_id === a[1]); if (!existing) this.customers.push({ id: a[0], paddle_customer_id: a[1], normalized_email: a[2] }); return { meta: { changes: existing ? 0 : 1 } }; }
    if (sql.startsWith("INSERT OR IGNORE INTO activation_codes")) { const existing = this.codes.find((row) => row.entitlement_id === a[1]); if (!existing) this.codes.push({ id: a[0], entitlement_id: a[1], code_hash: a[2], redeemed_at: a[4] }); return { meta: { changes: existing ? 0 : 1 } }; }
    if (sql.startsWith("INSERT INTO customers")) { this.customers.push({ id: a[0], paddle_customer_id: a[1], normalized_email: a[2] }); return { meta: { changes: 1 } }; }
    if (sql.startsWith("UPDATE customers")) { const row = this.customers.find((item) => item.id === a[2]); row.normalized_email = a[0]; return { meta: { changes: 1 } }; }
    if (sql.startsWith("INSERT INTO restore_requests")) { this.restores.push(a); return { meta: { changes: 1 } }; }
    if (sql.startsWith("UPDATE activations")) { const row = this.activations.find((item) => item.token_id === a[1]); if (row) row.last_seen_at = a[0]; return { meta: { changes: 1 } }; }
    return { meta: { changes: 0 } };
  }
  async batch(statements) {
    if (this.failNext === "entitlement_batch") { this.failNext = null; throw new Error("database unavailable"); }
    const results = [];
    for (const statement of statements) {
      const sql = statement.sql; const a = statement.args;
      if (sql.startsWith("INSERT OR IGNORE INTO customers")) { const existing = this.customers.find((row) => row.paddle_customer_id === a[1]); if (!existing) this.customers.push({ id: a[0], paddle_customer_id: a[1], normalized_email: a[2] }); results.push({ meta: { changes: existing ? 0 : 1 } }); continue; }
      if (sql.startsWith("UPDATE customers")) { const row = this.customers.find((item) => item.id === a[2]); if (row) row.normalized_email = a[0]; results.push({ meta: { changes: row ? 1 : 0 } }); continue; }
      if (sql.startsWith("INSERT OR IGNORE INTO entitlements")) { const existing = this.entitlements.find((row) => row.transaction_id === a[2] && row.product_key === a[3] && row.plan_key === a[4]); if (!existing) { const row = { id: a[0], customer_id: a[1], transaction_id: a[2], product_key: a[3], plan_key: a[4], status: a[6] }; if (a[5]) row.paddle_item_id = a[5]; this.entitlements.push(row); } results.push({ meta: { changes: existing ? 0 : 1 } }); continue; }
      if (sql.startsWith("INSERT INTO entitlements")) { this.entitlements.push({ id: a[0], customer_id: a[1], transaction_id: a[2], product_key: a[3], plan_key: a[4], status: a[5] }); results.push({ meta: { changes: 1 } }); continue; }
      if (sql.startsWith("INSERT OR IGNORE INTO activation_codes")) { const existing = this.codes.find((row) => row.entitlement_id === a[1]); if (!existing) this.codes.push({ id: a[0], entitlement_id: a[1], code_hash: a[2], redeemed_at: a[4] }); results.push({ meta: { changes: existing ? 0 : 1 } }); continue; }
      if (sql.startsWith("INSERT INTO activation_codes")) { this.codes.push({ id: a[0], entitlement_id: a[1], code_hash: a[2], redeemed_at: a[4], revoked_at: null }); results.push({ meta: { changes: 1 } }); continue; }
      if (sql.startsWith("INSERT INTO activations")) { const code = this.codes.find((row) => row.id === a[7] && !row.redeemed_at); if (!code) { results.push({ meta: { changes: 0 } }); continue; } this.activations.push({ id: a[0], entitlement_id: a[1], installation_id_hash: a[2], token_id: a[3], revoked_at: null }); results.push({ meta: { changes: 1 } }); continue; }
      if (sql.startsWith("UPDATE activation_codes SET redeemed_at")) { const row = this.codes.find((item) => item.id === a[1] && !item.redeemed_at); if (row) row.redeemed_at = a[0]; results.push({ meta: { changes: row ? 1 : 0 } }); continue; }
      if (sql.startsWith("UPDATE entitlements SET status = 'revoked'")) { const row = this.entitlements.find((item) => item.id === a[3] && item.status === "active"); if (row) { row.status = "revoked"; row.revoked_at = a[0]; row.revocation_reason = a[1]; row.updated_at = a[2]; } results.push({ meta: { changes: row ? 1 : 0 } }); continue; }
      if (sql.startsWith("UPDATE entitlement_purchase_guards SET status = 'revoked'")) { const rows = this.guards.filter((row) => row.transaction_id === a[1] && row.product_key === a[2] && row.plan_key === a[3] && row.status === "active"); rows.forEach((row) => { row.status = "revoked"; row.updated_at = a[0]; }); results.push({ meta: { changes: rows.length } }); continue; }
      if (sql.startsWith("UPDATE activation_codes SET revoked_at = ?")) { const rows = this.codes.filter((row) => row.entitlement_id === a[1]); rows.forEach((row) => { row.revoked_at = a[0]; }); results.push({ meta: { changes: rows.length } }); continue; }
      if (sql.startsWith("UPDATE activations SET revoked_at = ?")) { const rows = this.activations.filter((row) => row.entitlement_id === a[1] && !row.revoked_at); rows.forEach((row) => { row.revoked_at = a[0]; }); results.push({ meta: { changes: rows.length } }); continue; }
      if (sql.startsWith("UPDATE entitlements SET status = 'active'")) { const row = this.entitlements.find((item) => item.id === a[1] && item.status === "revoked"); if (row) { row.status = "active"; row.revoked_at = null; row.revocation_reason = null; row.updated_at = a[0]; } results.push({ meta: { changes: row ? 1 : 0 } }); continue; }
      if (sql.startsWith("UPDATE entitlement_purchase_guards SET status = 'active'")) { const rows = this.guards.filter((row) => row.transaction_id === a[1] && row.product_key === a[2] && row.plan_key === a[3]); rows.forEach((row) => { row.status = "active"; row.updated_at = a[0]; }); results.push({ meta: { changes: rows.length } }); continue; }
      if (sql.startsWith("UPDATE activation_codes SET revoked_at = NULL")) { const rows = this.codes.filter((row) => row.entitlement_id === a[0]); rows.forEach((row) => { row.revoked_at = null; }); results.push({ meta: { changes: rows.length } }); continue; }
      if (sql.startsWith("UPDATE activations SET revoked_at = NULL")) { const rows = this.activations.filter((row) => row.entitlement_id === a[0]); rows.forEach((row) => { row.revoked_at = null; }); results.push({ meta: { changes: rows.length } }); continue; }
    }
    return results;
  }
}

function dbEnv() { const env = envBase(); env.LICENSE_DB = new FakeDb(); return env; }
async function signedRequest(body, timestamp = Math.floor(Date.now() / 1000), extraHeaders = {}) { const raw = JSON.stringify(body); const hash = createHmac("sha256", secret).update(`${timestamp}:${raw}`).digest("hex"); return new Request("https://example.test/api/paddle/webhook", { method: "POST", headers: { "Paddle-Signature": `ts=${timestamp};h1=${hash}`, ...extraHeaders }, body: raw }); }
function eventFor(priceId = prices.standard, eventId = "evt_1", overrides = {}) { return { event_id: eventId, event_type: "transaction.completed", occurred_at: new Date().toISOString(), data: { id: `txn_${eventId}`, customer_id: "ctm_1", customer: { email: "Buyer@Example.com" }, items: [{ price: { id: priceId } }], ...overrides } }; }
async function fulfill(env, priceId = prices.standard, eventId = "evt_1", overrides = {}) { const response = await handleRequest(await signedRequest(eventFor(priceId, eventId, overrides)), env); return response.json(); }
function adjustmentFor(eventId, transactionId, action = "refund", status = "approved", overrides = {}) { return { event_id: eventId, event_type: eventId.startsWith("updated_") ? "adjustment.updated" : "adjustment.created", occurred_at: new Date().toISOString(), data: { id: `adj_${transactionId}`, transaction_id: transactionId, customer_id: "ctm_1", action, type: "full", status, items: [], ...overrides } }; }
async function adjust(env, eventId, transactionId, action = "refund", status = "approved", overrides = {}) { const response = await handleRequest(await signedRequest(adjustmentFor(eventId, transactionId, action, status, overrides)), env); return response.json(); }

test("valid Paddle signature fulfills a standard entitlement", async () => { const env = dbEnv(); const result = await fulfill(env); assert.equal(result.fulfilled, 1); assert.deepEqual(env.LICENSE_DB.entitlements[0].product_key, "ledgerlift"); assert.equal(env.LICENSE_DB.entitlements[0].plan_key, "standard"); });
test("Plus price creates a Plus entitlement", async () => { const env = dbEnv(); const result = await fulfill(env, prices.plus, "evt_plus"); assert.equal(result.fulfilled, 1); assert.equal(env.LICENSE_DB.entitlements[0].plan_key, "plus"); });
test("invalid signature is rejected", async () => { const env = dbEnv(); const request = new Request("https://example.test/api/paddle/webhook", { method: "POST", headers: { "Paddle-Signature": "ts=1;h1=bad" }, body: "{}" }); const response = await handleRequest(request, env); assert.equal(response.status, 400); });
test("stale signature is rejected", async () => { const env = dbEnv(); const response = await handleRequest(await signedRequest({}, 1), env); assert.equal(response.status, 400); });
test("duplicate events do not fulfill twice", async () => { const env = dbEnv(); await fulfill(env); const result = await fulfill(env); assert.equal(result.duplicate, true); assert.equal(env.LICENSE_DB.entitlements.length, 1); });
test("a second completed transaction for the same customer and plan is recorded without issuing access twice", async () => { const env = dbEnv(); await fulfill(env, prices.standard, "evt_first"); const result = await fulfill(env, prices.standard, "evt_second"); assert.equal(result.duplicate_purchase, true); assert.equal(result.fulfilled, 0); assert.equal(env.LICENSE_DB.entitlements.length, 1); assert.equal(env.LICENSE_DB.codes.length, 1); assert.equal(env.LICENSE_DB.events.get("evt_second").outcome, "duplicate_purchase"); });
test("a refund revokes the entitlement, activation code, and active devices", async () => { const env = dbEnv(); const purchase = await fulfill(env); const claim = await handleRequest(new Request("https://example.test/api/license/claim", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ activation_code: purchase.development_activation_codes[0], installation_id: "installation-refund" }) }), env); assert.equal(claim.status, 200); const result = await adjust(env, "adj_refund", "txn_evt_1"); assert.equal(result.revoked, 1); assert.equal(env.LICENSE_DB.entitlements[0].status, "revoked"); assert.ok(env.LICENSE_DB.entitlements[0].revoked_at); assert.ok(env.LICENSE_DB.codes[0].revoked_at); assert.ok(env.LICENSE_DB.activations[0].revoked_at); });
test("refund webhook replay is idempotent and a confirmed reversal restores access", async () => { const env = dbEnv(); await fulfill(env); await adjust(env, "adj_refund", "txn_evt_1"); const replay = await adjust(env, "adj_refund", "txn_evt_1"); assert.equal(replay.duplicate, true); const restored = await adjust(env, "updated_refund", "txn_evt_1", "refund", "reversed"); assert.equal(restored.restored, 1); assert.equal(env.LICENSE_DB.entitlements[0].status, "active"); assert.equal(env.LICENSE_DB.codes[0].revoked_at, null); });
test("an approved refund received before completion blocks later fulfillment", async () => { const env = dbEnv(); await adjust(env, "adj_before", "txn_before"); const result = await fulfill(env, prices.standard, "evt_before", { id: "txn_before" }); assert.equal(result.blocked_by_adjustment, true); assert.equal(result.fulfilled, 0); assert.equal(env.LICENSE_DB.entitlements.length, 0); });
test("a refunded plan may be purchased again without reviving the old entitlement", async () => { const env = dbEnv(); await fulfill(env); await adjust(env, "adj_refund", "txn_evt_1"); const result = await fulfill(env, prices.standard, "evt_repurchase"); assert.equal(result.fulfilled, 1); assert.equal(env.LICENSE_DB.entitlements.length, 2); assert.equal(env.LICENSE_DB.entitlements.filter((row) => row.status === "active").length, 1); });
test("a partial refund of a line item revokes that product entitlement", async () => { const env = dbEnv(); await fulfill(env, prices.standard, "evt_partial_purchase", { items: [{ id: "txnitm_1", price: { id: prices.standard } }] }); const result = await adjust(env, "adj_partial", "txn_evt_partial_purchase", "refund", "approved", { type: "partial", items: [{ item_id: "txnitm_1", type: "partial", amount: "100" }] }); assert.equal(result.revoked, 1); assert.equal(env.LICENSE_DB.entitlements[0].status, "revoked"); });
test("transaction detail line items persist Paddle transaction item IDs", async () => { const env = dbEnv(); await fulfill(env, prices.bundle, "evt_bundle_details", { details: { line_items: [{ id: "txnitm_bundle", price_id: prices.bundle }] } }); assert.equal(new Set(env.LICENSE_DB.entitlements.map((row) => row.paddle_item_id)).size, 1); assert.equal(env.LICENSE_DB.entitlements.every((row) => row.paddle_item_id === "txnitm_bundle"), true); });
test("a legacy bundle with missing item IDs still revokes on its single-line refund", async () => { const env = dbEnv(); await fulfill(env, prices.bundle, "evt_legacy_bundle"); const result = await adjust(env, "adj_legacy_bundle", "txn_evt_legacy_bundle", "refund", "approved", { type: "partial", items: [{ item_id: "txnitm_legacy_bundle", type: "full" }] }); assert.equal(result.revoked, 6); assert.equal(env.LICENSE_DB.entitlements.filter((row) => row.status === "active").length, 0); });
test("replaying a fulfilled adjustment can repair a prior zero-target result", async () => { const env = dbEnv(); await fulfill(env, prices.bundle, "evt_repair_bundle"); const event = adjustmentFor("updated_repair_bundle", "txn_evt_repair_bundle", "refund", "approved", { type: "partial", items: [{ item_id: "txnitm_repair_bundle", type: "full" }] }); env.LICENSE_DB.events.set("updated_repair_bundle", { status: "fulfilled", outcome: "revoked", processing_token: null, processing_started_at: null }); env.LICENSE_DB.adjustments.push({ adjustment_id: "adj_txn_evt_repair_bundle", transaction_id: "txn_evt_repair_bundle", customer_id: "ctm_1", action: "refund", adjustment_type: "partial", status: "approved", effect: "revoke", item_ids: '["txnitm_repair_bundle"]' }); const response = await handleRequest(await signedRequest(event), env); const result = await response.json(); assert.equal(response.status, 200); assert.equal(result.duplicate, true); assert.equal(result.revoked, 6); assert.equal(env.LICENSE_DB.entitlements.filter((row) => row.status === "active").length, 0); });
test("a bundle refund revokes exactly the bundle entitlement and five product entitlements", async () => { const env = dbEnv(); await fulfill(env, prices.bundle); const result = await adjust(env, "adj_bundle_refund", "txn_evt_1"); assert.equal(result.revoked, 6); assert.equal(env.LICENSE_DB.entitlements.filter((row) => row.status === "active").length, 0); });
test("a repeated bundle does not create a second suite marker when all five Plus products are already owned", async () => { const env = dbEnv(); await fulfill(env, prices.bundle, "evt_bundle_first"); const result = await fulfill(env, prices.bundle, "evt_bundle_second"); assert.equal(result.duplicate_purchase, true); assert.equal(result.fulfilled, 0); assert.equal(env.LICENSE_DB.entitlements.length, 6); assert.equal(env.LICENSE_DB.codes.length, 6); });
test("failed fulfillment remains retryable and later succeeds", async () => { const env = dbEnv(); env.LICENSE_DB.failNext = "entitlement_batch"; const first = await handleRequest(await signedRequest(eventFor()), env); assert.equal(first.status, 503); assert.equal(env.LICENSE_DB.events.get("evt_1").status, "failed"); assert.equal(env.LICENSE_DB.entitlements.length, 0); const second = await fulfill(env); assert.equal(second.fulfilled, 1); assert.equal(env.LICENSE_DB.events.get("evt_1").status, "fulfilled"); });
test("generic event registration failure is retriable, not a duplicate", async () => { const env = dbEnv(); env.LICENSE_DB.failNext = "event_insert"; const response = await handleRequest(await signedRequest(eventFor()), env); assert.equal(response.status, 503); assert.notEqual((await response.json()).duplicate, true); });
test("missing webhook email uses Paddle customer lookup", async () => { const env = dbEnv(); env.PADDLE_API_KEY = "server-only-test-key"; env.PADDLE_API_BASE_URL = "https://sandbox-api.paddle.com"; const originalFetch = globalThis.fetch; let calledUrl = ""; globalThis.fetch = async (url, options) => { calledUrl = String(url); assert.match(options.headers.Authorization, /^Bearer /); return new Response(JSON.stringify({ data: { email: "Lookup@Example.com" } }), { status: 200, headers: { "content-type": "application/json" } }); }; try { const result = await fulfill(env, prices.standard, "evt_lookup", { customer: {} }); assert.equal(result.fulfilled, 1); assert.equal(env.LICENSE_DB.customers[0].normalized_email, "lookup@example.com"); assert.match(calledUrl, /\/customers\/ctm_1$/); } finally { globalThis.fetch = originalFetch; } });
test("Paddle customer lookup failure is retriable", async () => { const env = dbEnv(); env.PADDLE_API_KEY = "server-only-test-key"; env.PADDLE_API_BASE_URL = "https://sandbox-api.paddle.com"; const originalFetch = globalThis.fetch; globalThis.fetch = async () => { throw new Error("network unavailable"); }; try { const response = await handleRequest(await signedRequest(eventFor(prices.standard, "evt_lookup_failed", { customer: {} })), env); assert.equal(response.status, 503); assert.equal((await response.json()).error, "customer_lookup_failed"); assert.equal(env.LICENSE_DB.events.get("evt_lookup_failed").status, "failed"); } finally { globalThis.fetch = originalFetch; } });
test("invalid customer email prevents fulfillment", async () => { const env = dbEnv(); env.PADDLE_API_KEY = "server-only-test-key"; env.PADDLE_API_BASE_URL = "https://sandbox-api.paddle.com"; const originalFetch = globalThis.fetch; globalThis.fetch = async () => new Response(JSON.stringify({ data: { email: "not-an-email" } }), { status: 200 }); try { const response = await handleRequest(await signedRequest(eventFor(prices.standard, "evt_invalid_email", { customer: {} })), env); assert.equal(response.status, 422); assert.equal((await response.json()).error, "invalid_customer_email"); assert.equal(env.LICENSE_DB.entitlements.length, 0); } finally { globalThis.fetch = originalFetch; } });
test("empty item list is rejected without recording fulfillment", async () => { const env = dbEnv(); const response = await handleRequest(await signedRequest(eventFor(prices.standard, "evt_empty", { items: [] })), env); assert.equal(response.status, 422); assert.equal((await response.json()).error, "unsupported_price"); assert.equal(env.LICENSE_DB.events.size, 0); });
test("unknown price IDs are rejected", async () => { const env = dbEnv(); const result = await fulfill(env, "pri_unknown"); assert.equal(result.error, "unsupported_price"); assert.equal(env.LICENSE_DB.entitlements.length, 0); });
test("bundle creates an explicit bundle entitlement plus five product Plus entitlements", async () => { const env = dbEnv(); const result = await fulfill(env, prices.bundle); assert.equal(result.fulfilled, 6); assert.equal(env.LICENSE_DB.entitlements.filter((row) => row.plan_key === "plus").length, 5); assert.deepEqual(env.LICENSE_DB.entitlements.find((row) => row.product_key === "suite"), { id: env.LICENSE_DB.entitlements.find((row) => row.product_key === "suite").id, customer_id: env.LICENSE_DB.entitlements[0].customer_id, transaction_id: "txn_evt_1", product_key: "suite", plan_key: "bundle", status: "active" }); });

test("product entitlement summary keeps LedgerLift ownership independent", () => {
  const free = summarizeEntitlements([]);
  assert.equal(free.highestLedgerLiftTier, "free");
  assert.equal(free.products.pixelport, "free");
  const ledgerStandard = summarizeEntitlements([{ product_key: "ledgerlift", plan_key: "standard", status: "active" }]);
  assert.equal(ledgerStandard.highestLedgerLiftTier, "standard");
  assert.equal(ledgerStandard.products.pixelport, "free");
  const pixelPlus = summarizeEntitlements([{ product_key: "pixelport", plan_key: "plus", status: "active" }]);
  assert.equal(pixelPlus.highestLedgerLiftTier, "free");
  const pixelStandard = summarizeEntitlements([{ product_key: "pixelport", plan_key: "standard", status: "active" }]);
  assert.equal(pixelStandard.products.pixelport, "standard");
  assert.equal(pixelStandard.products.ledgerlift, "free");
  const multiple = summarizeEntitlements([{ product_key: "ledgerlift", plan_key: "standard", status: "active" }, { product_key: "ledgerlift", plan_key: "plus", status: "active" }, { product_key: "calendarflow", plan_key: "standard", status: "active" }]);
  assert.equal(multiple.highestLedgerLiftTier, "plus");
  assert.equal(multiple.products.calendarflow, "standard");
  const revoked = summarizeEntitlements([{ product_key: "ledgerlift", plan_key: "plus", status: "revoked" }]);
  assert.equal(revoked.highestLedgerLiftTier, "free");
  const bundle = summarizeEntitlements([{ product_key: "suite", plan_key: "bundle", status: "active" }]);
  assert.equal(bundle.bundle, true);
  assert.equal(bundle.highestLedgerLiftTier, "plus");
  assert.equal(bundle.products.pixelport, "plus");
  const allIndividualPlus = summarizeEntitlements(["ledgerlift", "pixelport", "contactcraft", "calendarflow", "captionshift"].map((product_key) => ({ product_key, plan_key: "plus", status: "active" })));
  assert.equal(allIndividualPlus.bundle, false);
  assert.equal(allIndividualPlus.highestLedgerLiftTier, "plus");
});

test("product entitlement summary keeps ContactCraft ownership independent", () => {
  const contactStandard = summarizeEntitlements([{ product_key: "contactcraft", plan_key: "standard", status: "active" }]);
  assert.equal(contactStandard.products.contactcraft, "standard");
  assert.equal(contactStandard.products.ledgerlift, "free");
  assert.equal(contactStandard.products.pixelport, "free");
  const contactPlus = summarizeEntitlements([{ product_key: "contactcraft", plan_key: "standard", status: "active" }, { product_key: "contactcraft", plan_key: "plus", status: "active" }]);
  assert.equal(contactPlus.products.contactcraft, "plus");
  const otherProduct = summarizeEntitlements([{ product_key: "ledgerlift", plan_key: "plus", status: "active" }]);
  assert.equal(otherProduct.products.contactcraft, "free");
  const revoked = summarizeEntitlements([{ product_key: "contactcraft", plan_key: "plus", status: "revoked" }]);
  assert.equal(revoked.products.contactcraft, "free");
  const bundle = summarizeEntitlements([{ product_key: "suite", plan_key: "bundle", status: "active" }]);
  assert.equal(bundle.products.contactcraft, "plus");
});

test("product entitlement summary keeps CalendarFlow ownership independent", () => {
  const calendarStandard = summarizeEntitlements([{ product_key: "calendarflow", plan_key: "standard", status: "active" }]);
  assert.equal(calendarStandard.products.calendarflow, "standard");
  assert.equal(calendarStandard.products.ledgerlift, "free");
  assert.equal(calendarStandard.products.contactcraft, "free");
  const calendarPlus = summarizeEntitlements([{ product_key: "calendarflow", plan_key: "standard", status: "active" }, { product_key: "calendarflow", plan_key: "plus", status: "active" }]);
  assert.equal(calendarPlus.products.calendarflow, "plus");
  const otherProduct = summarizeEntitlements([{ product_key: "contactcraft", plan_key: "plus", status: "active" }]);
  assert.equal(otherProduct.products.calendarflow, "free");
  const revoked = summarizeEntitlements([{ product_key: "calendarflow", plan_key: "plus", status: "revoked" }]);
  assert.equal(revoked.products.calendarflow, "free");
  const bundle = summarizeEntitlements([{ product_key: "suite", plan_key: "bundle", status: "active" }]);
  assert.equal(bundle.products.calendarflow, "plus");
});

test("product entitlement summary keeps CaptionShift ownership independent", () => {
  const captionStandard = summarizeEntitlements([{ product_key: "captionshift", plan_key: "standard", status: "active" }]);
  assert.equal(captionStandard.products.captionshift, "standard");
  assert.equal(captionStandard.products.ledgerlift, "free");
  assert.equal(captionStandard.products.calendarflow, "free");
  const captionPlus = summarizeEntitlements([{ product_key: "captionshift", plan_key: "standard", status: "active" }, { product_key: "captionshift", plan_key: "plus", status: "active" }]);
  assert.equal(captionPlus.products.captionshift, "plus");
  const otherProduct = summarizeEntitlements([{ product_key: "ledgerlift", plan_key: "plus", status: "active" }]);
  assert.equal(otherProduct.products.captionshift, "free");
  const revoked = summarizeEntitlements([{ product_key: "captionshift", plan_key: "plus", status: "revoked" }]);
  assert.equal(revoked.products.captionshift, "free");
  const bundle = summarizeEntitlements([{ product_key: "suite", plan_key: "bundle", status: "active" }]);
  assert.equal(bundle.products.captionshift, "plus");
});
test("concurrent delivery allows one owner and makes the other retry", async () => { const env = dbEnv(); const responses = await Promise.all([handleRequest(await signedRequest(eventFor(prices.plus, "evt_concurrent")), env), handleRequest(await signedRequest(eventFor(prices.plus, "evt_concurrent")), env)]); const statuses = responses.map((response) => response.status).sort(); assert.deepEqual(statuses, [200, 409]); assert.equal(env.LICENSE_DB.entitlements.length, 1); const retry = await fulfill(env, prices.plus, "evt_concurrent"); assert.equal(retry.duplicate, true); assert.equal(env.LICENSE_DB.codes.length, 1); });
test("replayed fulfillment does not create another activation code", async () => { const env = dbEnv(); await fulfill(env); await fulfill(env); assert.equal(env.LICENSE_DB.entitlements.length, 1); assert.equal(env.LICENSE_DB.codes.length, 1); });
test("activation code is single-use and returns a signed entitlement", async () => { const env = dbEnv(); const result = await fulfill(env); const claim = await handleRequest(new Request("https://example.test/api/license/claim", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ activation_code: result.development_activation_codes[0], installation_id: "installation-123456789" }) }), env); assert.equal(claim.status, 200); const second = await handleRequest(new Request("https://example.test/api/license/claim", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ activation_code: result.development_activation_codes[0], installation_id: "installation-987654321" }) }), env); assert.equal(second.status, 400); });
test("invalid license signature is rejected", async () => { const env = dbEnv(); const response = await handleRequest(new Request("https://example.test/api/license/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entitlement: "bad.token" }) }), env); assert.equal(response.status, 401); });
test("revoked activation is rejected", async () => { const env = dbEnv(); const result = await fulfill(env); const claim = await handleRequest(new Request("https://example.test/api/license/claim", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ activation_code: result.development_activation_codes[0], installation_id: "installation-revoked" }) }), env); const token = (await claim.json()).entitlement; env.LICENSE_DB.activations[0].revoked_at = new Date().toISOString(); const verify = await handleRequest(new Request("https://example.test/api/license/verify", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ entitlement: token }) }), env); assert.equal(verify.status, 401); });
test("restore response is generic for valid and invalid email shapes", async () => { const env = dbEnv(); const request = (email) => new Request("https://example.test/api/license/restore/request", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email }) }); const a = await (await handleRequest(request("nobody@example.com"), env)).json(); const b = await (await handleRequest(request("not-an-email"), env)).json(); assert.deepEqual(a, b); });
test("health is minimal and directory routes serve their index assets", async () => { const env = dbEnv(); const health = await handleRequest(new Request("https://example.test/api/health"), env); assert.deepEqual(await health.json(), { status: "ok" }); const page = await handleRequest(new Request("https://example.test/ledgerlift/"), env); assert.equal(await page.text(), "static:/ledgerlift/index.html"); });
test("readiness reports incomplete production configuration without exposing secrets", async () => { const env = dbEnv(); const response = await handleRequest(new Request("https://example.test/api/readiness"), env); assert.equal(response.status, 503); const body = await response.json(); assert.equal(body.ready, false); assert.equal(body.checks.database, true); assert.equal(body.checks.licenseSigningSecret, true); assert.equal(body.checks.durableRateLimiter, false); assert.doesNotMatch(JSON.stringify(body), /sandbox|test_|live_|pri_/i); assert.equal(Object.hasOwn(body.checks, "PADDLE_API_KEY"), false); });
test("durable rate limiting can be required in production", async () => { const env = dbEnv(); env.REQUIRE_DURABLE_RATE_LIMITER = "true"; const response = await handleRequest(new Request("https://example.test/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "A", email: "buyer@example.com", topic: "General question", product: "LocalFile Toolkit", subject: "Hello", message: "A question", consent: true }) }), env); assert.equal(response.status, 429); });
test("production webhook accepts only current Paddle source IPs", async () => { const env = dbEnv(); env.DEVELOPMENT = "false"; env.PADDLE_ENFORCE_WEBHOOK_IPS = "true"; const originalFetch = globalThis.fetch; globalThis.fetch = async () => new Response(JSON.stringify({ data: { ipv4_cidrs: ["34.237.3.244/32"] } }), { status: 200, headers: { "content-type": "application/json" } }); try { const rejected = await handleRequest(await signedRequest(eventFor(prices.standard, "evt_ip_rejected"), undefined, { "CF-Connecting-IP": "203.0.113.10" }), env); assert.equal(rejected.status, 403); assert.equal((await rejected.json()).error, "paddle_ip_not_allowed"); assert.equal(env.LICENSE_DB.events.has("evt_ip_rejected"), false); const accepted = await handleRequest(await signedRequest(eventFor(prices.standard, "evt_ip_accepted"), undefined, { "CF-Connecting-IP": "34.237.3.244" }), env); assert.equal(accepted.status, 200); assert.equal((await accepted.json()).fulfilled, 1); } finally { globalThis.fetch = originalFetch; } });
test("contact endpoint rejects non-JSON and invalid input", async () => { const env = dbEnv(); const badType = await handleRequest(new Request("https://example.test/api/contact", { method: "POST", body: "x" }), env); assert.equal(badType.status, 400); const badEmail = await handleRequest(new Request("https://example.test/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "A", email: "bad", topic: "Other", product: "LocalFile Toolkit", subject: "Hi", message: "Hello", consent: true }) }), env); assert.equal(badEmail.status, 400); });
test("contact honeypot is silently discarded and setup mode is explicit", async () => { const env = dbEnv(); const hidden = await handleRequest(new Request("https://example.test/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ honeypot: "bot" }) }), env); assert.equal(hidden.status, 204); const response = await handleRequest(new Request("https://example.test/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "A", email: "buyer@example.com", topic: "General question", product: "LocalFile Toolkit", subject: "Hello", message: "A question", consent: true }) }), env); assert.equal(response.status, 503); assert.equal((await response.json()).setup_mode, true); });
test("refund endpoint rejects invalid input and supports setup mode", async () => { const env = dbEnv(); const invalid = await handleRequest(new Request("https://example.test/api/refund-request", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({}) }), env); assert.equal(invalid.status, 400); const response = await handleRequest(new Request("https://example.test/api/refund-request", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "A", email: "buyer@example.com", transaction_id: "txn_1", product: "LedgerLift", plan: "Standard", purchase_date: "2026-07-10", reason: "Technical problem", details: "Details", accurate: true }) }), env); assert.equal(response.status, 503); assert.equal((await response.json()).setup_mode, true); });
